apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "content-manager.fullname" . }}-frontend-nginx
  labels:
    {{- include "content-manager.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
