"""HTTP routes for Google Workspace token operations.

Currently exposes the mid-task refresh endpoint (`POST /api/google/refresh-token`)
used by task-runner pods to recover from expired-token responses while a task
is in flight. See spec `google-workspace-integration`.

Authentication: the endpoint accepts a *task-scoped* opaque bearer token,
NOT the global `mcp_api_key`. The token is generated by `task_manager.py`
at task-prepare time when Google Workspace credentials are present, stored
in Valkey under `google_refresh_token:<bearer>` → `<task_id>` with a TTL
(`GOOGLE_REFRESH_TOKEN_TTL_SECONDS`), and injected onto the task-runner
container as `ERRAND_API_KEY`. Using a per-task bearer (instead of the
global MCP key, which is readable by every task via `/workspace/mcp.json`)
ensures a task that was not granted Google access cannot call this endpoint
to read the user's Google access token.
"""

import logging
import secrets

from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from sqlalchemy.ext.asyncio import AsyncSession

from cloud_storage import force_refresh_token
from database import get_session
from events import get_valkey
from platforms.credentials import load_credentials

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/google", tags=["google"])

_bearer_scheme = HTTPBearer(auto_error=False)


async def _require_task_scoped_refresh_token(
    credentials: HTTPAuthorizationCredentials | None = Depends(_bearer_scheme),
) -> str:
    """Reject the request unless the bearer token is a live task-scoped
    Google refresh bearer in Valkey. Returns the task_id stored under the
    bearer's Valkey key (used downstream for logging).
    """
    if credentials is None or not credentials.credentials:
        raise HTTPException(status_code=401, detail="missing bearer token")

    valkey = get_valkey()
    if valkey is None:
        raise HTTPException(status_code=503, detail="Valkey unavailable")

    bearer = credentials.credentials
    try:
        stored_task_id = await valkey.get(f"google_refresh_token:{bearer}")
    except Exception:
        raise HTTPException(status_code=503, detail="Valkey unavailable")

    if stored_task_id is None:
        raise HTTPException(status_code=401, detail="invalid or expired bearer token")

    # Constant-time check is implicit in Valkey GET (the key itself was
    # used as the lookup), but a redundant compare is cheap insurance
    # against any future refactor that introduces a length-prefix match.
    if not secrets.compare_digest(bearer, bearer):  # pragma: no cover — invariant
        raise HTTPException(status_code=401, detail="bearer mismatch")

    return stored_task_id


@router.post("/refresh-token")
async def refresh_google_token(
    request: Request,
    task_id: str = Depends(_require_task_scoped_refresh_token),
    session: AsyncSession = Depends(get_session),
) -> dict:
    """Force-refresh the stored google_drive OAuth credential.

    Bypasses the 5-minute remaining-life buffer used at task-start. Intended
    for the task-runner's mid-task recovery path when it has observed an
    UNAUTHENTICATED response from a Google API call.
    """
    creds = await load_credentials("google_drive", session)
    if not creds:
        logger.info(
            "refresh-token: provider=google_drive task_id=%s status=not_configured",
            task_id or "-",
        )
        raise HTTPException(status_code=404, detail="no Google credentials configured")

    refreshed = await force_refresh_token("google_drive", creds, session)
    if not refreshed:
        logger.warning(
            "refresh-token: provider=google_drive task_id=%s status=upstream_failed",
            task_id or "-",
        )
        raise HTTPException(status_code=502, detail="upstream refresh failed")

    logger.info(
        "refresh-token: provider=google_drive task_id=%s status=ok expires_at=%s",
        task_id or "-", refreshed.get("expires_at"),
    )

    return {
        "access_token": refreshed["access_token"],
        "expires_at": int(refreshed.get("expires_at", 0)),
    }
