"""HTTP routes for Google Workspace token operations.

Currently exposes the mid-task refresh endpoint (`POST /api/google/refresh-token`)
used by task-runner pods to recover from expired-token responses while a task
is in flight. See spec `google-workspace-integration`.

Authentication: the endpoint accepts a *task-scoped* opaque bearer token,
NOT the global `mcp_api_key`. The token is generated by `task_manager.py`
at task-prepare time when Google Workspace credentials are present, stored
in Valkey under `google_refresh_token:<bearer>` → `<task_id>` with a TTL
(`GOOGLE_REFRESH_TOKEN_TTL_SECONDS`), and injected onto the task-runner
container as `ERRAND_API_KEY`. Using a per-task bearer (instead of the
global MCP key, which is readable by every task via `/workspace/mcp.json`)
ensures a task that was not granted Google access cannot call this endpoint
to read the user's Google access token.
"""

import logging

from fastapi import APIRouter, Depends, HTTPException, Request
from sqlalchemy.ext.asyncio import AsyncSession

from cloud_storage import force_refresh_token
from database import get_session
from platforms.credentials import load_credentials
from workspace_refresh_auth import GOOGLE_TASK_BEARER_PREFIX, require_refresh_bearer

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/google", tags=["google"])

# The endpoint accepts either the per-task Google refresh bearer (issued by
# task_manager) or the workspace-scoped gateway bearer (issued when the shared
# workspace is enabled) — both are consulted by this shared dependency.
_require_refresh_bearer = require_refresh_bearer(GOOGLE_TASK_BEARER_PREFIX)


@router.post("/refresh-token")
async def refresh_google_token(
    request: Request,
    task_id: str = Depends(_require_refresh_bearer),
    session: AsyncSession = Depends(get_session),
) -> dict:
    """Force-refresh the stored google_drive OAuth credential.

    Bypasses the 5-minute remaining-life buffer used at task-start. Intended
    for the task-runner's mid-task recovery path when it has observed an
    UNAUTHENTICATED response from a Google API call.
    """
    creds = await load_credentials("google_drive", session)
    if not creds:
        logger.info(
            "refresh-token: provider=google_drive task_id=%s status=not_configured",
            task_id or "-",
        )
        raise HTTPException(status_code=404, detail="no Google credentials configured")

    refreshed = await force_refresh_token("google_drive", creds, session)
    if not refreshed:
        logger.warning(
            "refresh-token: provider=google_drive task_id=%s status=upstream_failed",
            task_id or "-",
        )
        raise HTTPException(status_code=502, detail="upstream refresh failed")

    logger.info(
        "refresh-token: provider=google_drive task_id=%s status=ok expires_at=%s",
        task_id or "-", refreshed.get("expires_at"),
    )

    return {
        "access_token": refreshed["access_token"],
        "expires_at": int(refreshed.get("expires_at", 0)),
    }
