apiVersion: v1
kind: Service
metadata:
  name: {{ include "errand.fullname" . }}-backend
  labels:
    {{- include "errand.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8000
