{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "errand.fullname" . }}-worker
  labels:
    {{- include "errand.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "errand.fullname" . }}-worker
  pollingInterval: {{ .Values.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  triggers:
    - type: metrics-api
      metadata:
        targetValue: {{ .Values.keda.threshold | quote }}
        url: "http://{{ include "errand.fullname" . }}-backend:{{ .Values.backend.service.port }}/metrics/queue"
        valueLocation: "queue_depth"
{{- end }}
